# Generated by Django 4.0.4 on 2022-05-21 10:08

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название статьи')),
                ('label', models.ImageField(blank=True, upload_to='uploads/labels', verbose_name='Лого статьи')),
            ],
            options={
                'verbose_name': 'Статья курса',
                'verbose_name_plural': 'Статьи курса',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название екстра задания')),
                ('text', models.TextField(verbose_name='Текст екстра задания')),
                ('image', models.ImageField(blank=True, upload_to='uploads/extra', verbose_name='Картинка для задания')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
            options={
                'verbose_name': 'Екстра задание',
                'verbose_name_plural': 'Екстра задания',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название для бонуса')),
                ('text', models.TextField(verbose_name='Текст для бонуса')),
                ('image', models.ImageField(blank=True, upload_to='uploads/bonus/', verbose_name='Картинка для бонуса')),
                ('pdf', models.FileField(blank=True, upload_to='uploads/bonus', verbose_name='ПДФка для бонуса')),
                ('meditation', models.FileField(blank=True, upload_to='uploads/meditation', verbose_name='Медитация')),
                ('instruction', models.FileField(default='settings.MEDIA_ROOT/uploads/extra/instruction.pdf', storage=django.core.files.storage.FileSystemStorage(location='/Users/art/Documents/develop/cource/backend/media'), upload_to='uploads/meditation', verbose_name='Инструкция к медитации')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
            options={
                'verbose_name': 'Бонус задание',
                'verbose_name_plural': 'Бонус задания',
            },
        ),
        migrations.CreateModel(
            name='ArticleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, upload_to='uploads/articles', verbose_name='Картинка для статьи')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
            options={
                'verbose_name': 'Основной текст статьи',
                'verbose_name_plural': 'Теста для статей курса',
            },
        ),
    ]
