# Generated by Django 4.0.4 on 2022-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_blocked',
            field=models.BooleanField(default=True, verbose_name='Заблокированно?'),
        ),
    ]
