# Generated by Django 4.0.4 on 2022-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletext',
            options={'verbose_name': 'Основной текст статьи', 'verbose_name_plural': 'Текст для статей курса'},
        ),
        migrations.RenameField(
            model_name='articletext',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='articletext',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='uploads/articles', verbose_name='Картинка для статьи'),
        ),
        migrations.AddField(
            model_name='articletext',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='uploads/articles', verbose_name='Картинка для статьи'),
        ),
    ]
