# Generated by Django 4.0.4 on 2022-05-23 09:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articletext_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletext',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст статьи'),
        ),
    ]
