# Generated by Django 4.0.4 on 2022-05-23 09:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articletext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст для бонуса'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст екстра задания'),
        ),
    ]
