# Generated by Django 4.0.4 on 2022-05-23 11:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_rename_text_bonus_text_bonus_bonus_text_meditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='instruction',
            field=models.FileField(default='settings.MEDIA_ROOT/uploads/meditation/как_правильно_медитировать.pdf', storage=django.core.files.storage.FileSystemStorage(location='/Users/art/Documents/develop/cource/backend/media'), upload_to='uploads/meditation', verbose_name='Инструкция к медитации'),
        ),
    ]
