# Generated by Django 4.0.4 on 2022-05-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_text_bonus_bonus_text_bonus_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='text_bonus_1',
            new_name='text_bonus',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='text_bonus_2',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='text_meditation',
        ),
    ]
