# Generated by Django 4.0.4 on 2022-05-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_rename_text_bonus_1_bonus_text_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='instruction',
            field=models.FileField(default='uploads/meditation/как_правильно_медитировать.pdf', upload_to='uploads/meditation', verbose_name='Инструкция к медитации'),
        ),
    ]
