# Generated by Django 4.0.4 on 2022-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_bonus_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='instruction',
            field=models.FileField(blank=True, default='uploads/meditation/как_правильно_медитировать.pdf', upload_to='uploads/meditation', verbose_name='Инструкция к медитации'),
        ),
    ]
