# Generated by Django 4.0.4 on 2022-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_bonus_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletext',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='uploads/articles', verbose_name='Картинка для статьи 1'),
        ),
        migrations.AlterField(
            model_name='articletext',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='uploads/articles', verbose_name='Картинка для статьи 2'),
        ),
        migrations.AlterField(
            model_name='articletext',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='uploads/articles', verbose_name='Картинка для статьи 3'),
        ),
    ]
